description: >
  Testing exceptions
runExportedFunction: 0
# testOnly: true
expectException: "My uncaught exception"
expectedPrintout: foo
assertionCount: 12