description: >
  Testing exceptions
runExportedFunction: 0
testOnly: false
expectException: "My uncaught exception"
expectedPrintout: foo
assertionCount: 11